name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool restore

    - name: Build
      run: npm run build
      
    - name: Publish
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
