name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  #  
  #  - uses: actions/cache@v3
  #    id: cache
  #    with:
  #      path: ~/.nuget/packages
  #      key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
  #      restore-keys: |
  #        ${{ runner.os }}-nuget-
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Restore dependencies
  #    if: steps.cache.outputs.cache-hit != 'true'
      run: |
        dotnet restore
        dotnet tool restore

#    - name: Setup Wrangler
#      uses: vanhanenjjv/setup-wrangler@main
#      with:
#        apiToken: ${{ secrets.CF_API_TOKEN }}
#        accountId: ${{ secrets.CF_ACCOUNT_ID }}


    - name: Build
      run: npm run build

    - name: Publish
      run: wrangler publish
